### ISSUE TITLE
Add a second clock face to TimeShift app

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/time_shift#3]
https://docs.flutter.dev/clock

**Comment by eseidel** [comment]
Probably I'd make the main able to import different clocks based on some environment variable and then be able to build either with/without that environment variable to produce different flavors of the code.  I believe Dart tree shaking should shake out all the dead code of the unused clock, thus allowing the code-push of a re-build with the environ toggled to end up as a meaningful patch (as though someone had replaced the clock)?

Not sure.  Lots of other ways one could imagine improving time-shift.  The goal of the app is to just be a way for us to test end-to-end shorebird, including through submission to the play store.

Speaking of which, I think it's still currently in "public testing" rather than "published' we could move it to "published" as well.

**Comment by bryanoltman** [comment]
Closed by https://github.com/shorebirdtech/time_shift/pull/5
